### ISSUE TITLE
启动之后

### ISSUE THREAD

**Issue by kgdngitfk** [kingston-csj/mmorpg#2]
在ide中把server和client都启动了，只有两个console输出了启动日志，接下来呢？client和server的交互什么都看不到

**Comment by kingston-csj** [comment]
这段日子比较忙，等空闲的时候会搞多点代码上去，也会搞一些机器人测试功能。

**Comment by kingston-csj** [comment]
客户端已经提交了一段通信协议，后续会继续拓展。
