### ISSUE TITLE
事务

### ISSUE THREAD

**Issue by Zerision** [kingston-csj/mmorpg#9]
事务使用@Transactional(rollbackFor = Exception.class)怎么无效的,表的引擎也没错

**Comment by kingston-csj** [comment]
> 事务使用@transactional(rollbackFor = Exception.class)怎么无效的,表的引擎也没错

无效是怎么表现呢？

**Comment by kingston-csj** [comment]
游戏基本也没有事务的业务需求，大部分是基于内存数据更改。
